#!/usr/bin/env bash

cargo build --release
mkdir ohmk
cp target/release/ohmk ohmk/
cp install ohmk/
# cp uninstall ohmk/
cp -r shell/ ohmk/
cargo build --release --bin generate-config
cp target/release/generate-config ohmk/
